(autoload 'unfill-paragraph "utils" nil t)
(autoload 'syntax-highlight-region "utils" nil t)
(autoload 'syntax-highlight-region-span "utils" nil t)
(autoload 'jde-mode "jde" nil t)
(autoload 'jde-maven-build "jde-maven" nil t)
(autoload 'chop-move-up "chop" nil t)
(autoload 'chop-move-down "chop" nil t)
(autoload 'count-words "counting" nil t)
(autoload 'ioke-mode "ioke-mode" nil t)
(autoload 'seph-mode "seph-mode" nil t)
(autoload 'run-ioke "inf-ioke" nil t)
(autoload 'run-seph "inf-seph" nil t)
(autoload 'ansi-color-for-comint-mode-on "ansi-color" nil t)
(autoload 'speedbar-make-specialized-keymap "jde" nil t)
(autoload 'json-fix "json-fix" nil t)
(autoload 'org-tree-slide-mode "org-tree-slide" nil t)
(autoload 'ido-mode "ido" nil t)
(autoload 'fontize-set-default-font "fontize" nil t)
(autoload 'fontize-decrease-font-size "fontize" nil t)
(autoload 'ruby-insert-end "ruby-insert-end" nil t)

(provide 'emacs-require)
