(eval-when-compile    (require 'color-theme))
(defun color-theme-ola-dark ()
  (interactive)
  (color-theme-install
   '(color-theme-ola-dark
     ((background-color . "#232323")
      (background-mode . dark)
      (cursor-color . "#5A647E")
      (foreground-color . "#E6E1DC"))
     ((compilation-message-face . underline)
      (erc-button-face . erc-button)
      (erc-button-mouse-face . highlight)
      (erc-button-nickname-face . erc-nick-default-face)
      (ibuffer-deletion-face . error)
      (ibuffer-filter-group-name-face . bold)
      (ibuffer-marked-face . warning)
      (ibuffer-title-face . font-lock-type-face)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . match)
      (org-goto-interface . outline)
      (tags-tag-face . default)
      (widget-mouse-face . highlight))
     (default ((t (nil))))
     (bg:erc-color-face0 ((t (:background "White"))))
     (bg:erc-color-face1 ((t (:background "black"))))
     (bg:erc-color-face10 ((t (:background "lightblue1"))))
     (bg:erc-color-face11 ((t (:background "cyan"))))
     (bg:erc-color-face12 ((t (:background "blue"))))
     (bg:erc-color-face13 ((t (:background "deeppink"))))
     (bg:erc-color-face14 ((t (:background "gray50"))))
     (bg:erc-color-face15 ((t (:background "gray90"))))
     (bg:erc-color-face2 ((t (:background "blue4"))))
     (bg:erc-color-face3 ((t (:background "green4"))))
     (bg:erc-color-face4 ((t (:background "red"))))
     (bg:erc-color-face5 ((t (:background "brown"))))
     (bg:erc-color-face6 ((t (:background "purple"))))
     (bg:erc-color-face7 ((t (:background "orange"))))
     (bg:erc-color-face8 ((t (:background "yellow"))))
     (bg:erc-color-face9 ((t (:background "green"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (border ((t (nil))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (button ((t (:underline t :foreground "cyan1"))))
     (c-annotation-face ((t (:foreground "gray"))))
     (c-nonbreakable-space-face ((t (:bold t :weight bold :background "white" :foreground "black"))))
     (calendar-today ((t (:underline t))))
     (cider-error-highlight-face ((t (:underline (:style wave :color "red")))))
     (cider-warning-highlight-face ((t (:underline (:style wave :color "yellow")))))
     (clojure-test-error-face ((t (:background "orange4"))))
     (clojure-test-failure-face ((t (:background "firebrick"))))
     (clojure-test-success-face ((t (:background "green" :foreground "black"))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "cyan"))))
     (compilation-column-number ((t (:foreground "RoyalBlue"))))
     (compilation-error ((t (:bold t :weight bold :foreground "Pink"))))
     (compilation-info ((t (:bold t :weight bold :foreground "Green1"))))
     (compilation-line-number ((t (:foreground "MediumBlue"))))
     (compilation-mode-line-exit ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (compilation-mode-line-fail ((t (:bold t :foreground "Red1" :weight bold))))
     (compilation-mode-line-run ((t (:bold t :foreground "DarkOrange" :weight bold))))
     (compilation-warning ((t (:bold t :weight bold :foreground "DarkOrange"))))
     (completions-annotations ((t (:italic t :slant italic))))
     (completions-common-part ((t (:family "Menlo" :foundry "bitstream" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "white" :background "black" :stipple nil :height 136))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (cursor ((t (:background "white"))))
     (custom-button ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-mouse ((t (:background "grey90" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-pressed ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (custom-button-pressed-unraised ((t (:underline t :foreground "violet"))))
     (custom-button-unraised ((t (:underline t))))
     (custom-changed ((t (:background "blue1" :foreground "white"))))
     (custom-comment ((t (:background "dim gray"))))
     (custom-comment-tag ((t (:foreground "gray80"))))
     (custom-documentation ((t (nil))))
     (custom-face-tag ((t (:bold t :weight bold :foreground "light blue"))))
     (custom-group-subtitle ((t (:bold t :weight bold))))
     (custom-group-tag ((t (:bold t :family "Sans Serif" :foreground "light blue" :weight bold :height 1.2))))
     (custom-group-tag-1 ((t (:bold t :family "Sans Serif" :foreground "pink" :weight bold :height 1.2))))
     (custom-invalid ((t (:background "red1" :foreground "yellow1"))))
     (custom-link ((t (:underline t :foreground "cyan1"))))
     (custom-modified ((t (:background "blue1" :foreground "white"))))
     (custom-rogue ((t (:background "black" :foreground "pink"))))
     (custom-saved ((t (:underline t))))
     (custom-set ((t (:background "white" :foreground "blue1"))))
     (custom-state ((t (:foreground "lime green"))))
     (custom-themed ((t (:background "blue1" :foreground "white"))))
     (custom-variable-button ((t (:bold t :underline t :weight bold))))
     (custom-variable-tag ((t (:bold t :foreground "light blue" :weight bold))))
     (custom-visibility ((t (:underline t :foreground "cyan1" :height 0.8))))
     (diary ((t (:foreground "yellow1"))))
     (dired-directory ((t (:foreground "firebrick"))))
     (dired-flagged ((t (:bold t :weight bold :foreground "Pink"))))
     (dired-header ((t (:foreground "SteelBlue"))))
     (dired-ignored ((t (:foreground "grey70"))))
     (dired-mark ((t (:foreground "gray"))))
     (dired-marked ((t (:bold t :weight bold :foreground "DarkOrange"))))
     (dired-perm-write ((t (:foreground "DarkGreen"))))
     (dired-symlink ((t (:foreground "MediumBlue"))))
     (dired-warning ((t (:bold t :foreground "Pink" :weight bold))))
     (eieio-custom-slot-tag-face ((t (:foreground "light blue"))))
     (eldoc-highlight-function-argument ((t (:bold t :weight bold))))

     ;; ERC
     (erc-action-face ((t ( :background "#232323" :foreground "#00ff00" :weight bold :underline nil))))
     (erc-bold-face ((t (:background "#232323" :foreground "#00ff00" :weight bold :underline nil))))
     (erc-button ((t (:background "#232323" :foreground "#00ff00" :weight bold :underline nil))))
     (erc-command-indicator-face ((t ( :background "#232323" :foreground "#00ff00" :weight bold :underline nil))))
     (erc-current-nick-face ((t (:background "#232323" :foreground "#228B22" :weight bold :underline nil))))
     (erc-dangerous-host-face ((t (:background "#232323" :foreground "#ff00f0" :weight normal :underline nil))))
     (erc-default-face ((t (:background "#232323" :foreground "#00ff00" :weight normal :underline nil))))
     (erc-direct-msg-face ((t (:background "#232323" :foreground "#98FB98" :weight normal :underline nil))))
     (erc-error-face ((t (:background "#232323" :foreground "#ff00f0" :weight bold :underline nil))))
     (erc-fool-face ((t (:background "#232323" :foreground "dim gray" :weight normal :underline nil))))
     (erc-header-line ((t (:background "gray90" :foreground "gray20" :weight normal :underline nil))))
     (erc-input-face ((t (:background "#232323" :foreground "#8FBC8F" :weight normal :underline nil))))
     (erc-inverse-face ((t (:background "Black" :foreground "White" :weight normal :underline nil))))
     (erc-keyword-face ((t (:background "#232323" :foreground "pale green" :weight bold :underline nil))))
     (erc-my-nick-face ((t (:background "#232323" :foreground "#8FBC8F" :weight bold :underline nil))))
     (erc-nick-default-face ((t (:background "#232323" :foreground "#228B22" :weight bold :underline nil))))
     (erc-nick-msg-face ((t (:background "#232323" :foreground "#98FB98" :weight bold :underline nil))))
     (erc-notice-face ((t (:background "#232323" :foreground "#66CDAA" :weight bold :underline nil))))
     (erc-pal-face ((t (:background "#232323" :foreground "Magenta" :weight bold :underline nil))))
     (erc-prompt-face ((t (:background "#232323" :foreground "#48D1CC" :weight bold :underline nil))))
     (erc-timestamp-face ((t (:background "#232323" :foreground "#6B8E23" :weight bold :underline nil))))
     (erc-underline-face ((t (:background "#232323" :foreground "#00ff00" :weight normal :underline t))))

     (error ((t (:bold t :foreground "Pink" :weight bold))))
     (escape-glyph ((t (:foreground "cyan"))))
     (fg:erc-color-face0 ((t (:foreground "White"))))
     (fg:erc-color-face1 ((t (:foreground "black"))))
     (fg:erc-color-face10 ((t (:foreground "lightblue1"))))
     (fg:erc-color-face11 ((t (:foreground "cyan"))))
     (fg:erc-color-face12 ((t (:foreground "blue"))))
     (fg:erc-color-face13 ((t (:foreground "deeppink"))))
     (fg:erc-color-face14 ((t (:foreground "gray50"))))
     (fg:erc-color-face15 ((t (:foreground "gray90"))))
     (fg:erc-color-face2 ((t (:foreground "blue4"))))
     (fg:erc-color-face3 ((t (:foreground "green4"))))
     (fg:erc-color-face4 ((t (:foreground "red"))))
     (fg:erc-color-face5 ((t (:foreground "brown"))))
     (fg:erc-color-face6 ((t (:foreground "purple"))))
     (fg:erc-color-face7 ((t (:foreground "orange"))))
     (fg:erc-color-face8 ((t (:foreground "yellow"))))
     (fg:erc-color-face9 ((t (:foreground "green"))))
     (file-name-shadow ((t (:foreground "grey70"))))
     (fixed-pitch ((t (:family "Monospace"))))
     (font-lock-builtin-face ((t (:foreground "#D0D0FF"))))
     (font-lock-comment-face ((t (:foreground "#BC9458" :italic t))))
     (font-lock-constant-face ((t (:foreground "#6D9CBE"))))
     (font-lock-doc-string-face ((t (:foreground "#A5C261"))))
     (font-lock-function-name-face ((t (:foreground "#FFC66D"))))
     (font-lock-keyword-face ((t (:foreground "#CC7833"))))
     (font-lock-preprocessor-face ((t (:foreground "#CC7833"))))
     (font-lock-reference-face ((t (:foreground "LightSteelBlue"))))
     (font-lock-string-face ((t (:foreground "#A5C261"))))
     (font-lock-type-face ((t (:foreground "white"))))
     (font-lock-variable-name-face ((t (:foreground "LightSteelBlue"))))
     (font-lock-warning-face ((t (:foreground "Pink"))))
     (fringe ((t (:background "grey10"))))
     (glyphless-char ((t (:height 0.6))))
     (header-line ((t (:box (:line-width -1 :style released-button) :background "grey20" :foreground "grey90" :box nil))))
     (help-argument-name ((t (:italic t :slant italic))))
     (highlight ((t (:background "darkolivegreen"))))
     (holiday ((t (:background "chocolate4"))))
     (ido-first-match ((t (:bold t :weight bold))))
     (ido-incomplete-regexp ((t (:bold t :foreground "Pink" :weight bold))))
     (ido-indicator ((t (:background "red1" :foreground "yellow1" :width condensed))))
     (ido-only-match ((t (:foreground "ForestGreen"))))
     (ido-subdir ((t (:foreground "red1"))))
     (ido-virtual ((t (:foreground "SlateBlue"))))
     (info-header-node ((t (:italic t :bold t :weight bold :slant italic :foreground "white"))))
     (info-header-xref ((t (:foreground "cyan1" :underline t))))
     (info-menu-header ((t (:bold t :family "Sans Serif" :weight bold))))
     (info-menu-star ((t (:foreground "red1"))))
     (info-node ((t (:italic t :bold t :foreground "white" :slant italic :weight bold))))
     (info-title-1 ((t (:bold t :weight bold :family "Sans Serif" :height 1.728))))
     (info-title-2 ((t (:bold t :family "Sans Serif" :weight bold :height 1.44))))
     (info-title-3 ((t (:bold t :weight bold :family "Sans Serif" :height 1.2))))
     (info-title-4 ((t (:bold t :family "Sans Serif" :weight bold))))
     (info-xref ((t (:underline t :foreground "cyan1"))))
     (info-xref-visited ((t (:foreground "violet" :underline t))))
     (ioke-font-lock-api-cell-face ((t (:foreground "light goldenrod"))))
     (ioke-font-lock-expression-face ((t (:foreground "light goldenrod"))))
     (ioke-font-lock-known-kind-face ((t (:foreground "DarkRed"))))
     (ioke-font-lock-number-face ((t (:foreground "LightSalmon"))))
     (ioke-font-lock-object-assign-face ((t (:foreground "LightSteelBlue"))))
     (ioke-font-lock-object-mimic-face ((t (:foreground "medium blue"))))
     (ioke-font-lock-operator-name-face ((t (:foreground "CornflowerBlue"))))
     (ioke-font-lock-operator-symbol-face ((t (:foreground "deep sky blue"))))
     (ioke-font-lock-regexp-face ((t (:foreground "DeepPink"))))
     (isearch ((t (:background "palevioletred2" :foreground "brown4"))))
     (isearch-fail ((t (:background "red4"))))
     (italic ((t (:italic t :slant italic))))

     ;; JDE (Java)
     (jde-bug-breakpoint-cursor ((t (:background "brown" :foreground "cyan"))))
     (jde-db-active-breakpoint-face ((t (:background "red" :foreground "black"))))
     (jde-db-requested-breakpoint-face ((t (:background "yellow" :foreground "black"))))
     (jde-db-spec-breakpoint-face ((t (:background "green" :foreground "black"))))
     (jde-java-font-lock-api-face ((t (:foreground "DarkRed"))))
     (jde-java-font-lock-bold-face ((t (:bold t :weight bold))))
     (jde-java-font-lock-code-face ((t (nil))))
     (jde-java-font-lock-constant-face ((t (:foreground "BlueViolet"))))
     (jde-java-font-lock-constructor-face ((t (:foreground "LightSteelBlue"))))
     (jde-java-font-lock-doc-tag-face ((t (:foreground "light coral"))))
     (jde-java-font-lock-italic-face ((t (:italic t :slant italic))))
     (jde-java-font-lock-javadoc-face ((t (:foreground "RoyalBlue"))))
     (jde-java-font-lock-link-face ((t (:foreground "blue" :underline t :slant normal))))
     (jde-java-font-lock-modifier-face ((t (:foreground "LightSteelBlue"))))
     (jde-java-font-lock-number-face ((t (:foreground "LightSalmon"))))
     (jde-java-font-lock-operator-face ((t (:foreground "medium blue"))))
     (jde-java-font-lock-package-face ((t (:foreground "SlateGray4"))))
     (jde-java-font-lock-pre-face ((t (nil))))
     (jde-java-font-lock-private-face ((t (:foreground "LightSteelBlue"))))
     (jde-java-font-lock-protected-face ((t (:foreground "LightSteelBlue"))))
     (jde-java-font-lock-public-face ((t (:foreground "LightSteelBlue"))))
     (jde-java-font-lock-underline-face ((t (:underline t))))
     (lazy-highlight ((t (:background "paleturquoise4"))))
     (link ((t (:foreground "cyan1" :underline t))))
     (link-visited ((t (:underline t :foreground "violet"))))
     (match ((t (:background "RoyalBlue3"))))
     (menu ((t (nil))))
     (minibuffer-prompt ((t (:foreground "cyan"))))
     (mmm-cleanup-submode-face ((t (:background "Wheat"))))
     (mmm-code-submode-face ((t (:background "LavenderBlush2" :foreground "Black"))))
     (mmm-comment-submode-face ((t (:background "tan1" :foreground "Red"))))
     (mmm-declaration-submode-face ((t (:background "Aquamarine"))))
     (mmm-default-submode-face ((t (:background "gray85"))))
     (mmm-delimiter-face ((t (nil))))
     (mmm-init-submode-face ((t (:background "Pink"))))
     (mmm-output-submode-face ((t (:background "LemonChiffon2" :foreground "Black"))))
     (mmm-special-submode-face ((t (:background "MediumSpringGreen"))))
     ;; (mode-line ((t (:background "#A5BAF1" :foreground "black"))))
     ;; (mode-line-buffer-id ((t (:background "#A5BAF1" :foreground "black"))))
     ;; (mode-line-mousable ((t (:background "#A5BAF1" :foreground "black"))))
     ;; (mode-line-mousable-minor-mode ((t (:background"#A5BAF1" :foreground "black"))))
     (mode-line ((t (:background "#343434" :foreground "#E6E1DC"))))
     (mode-line-inactive ((t (:background "#282828" :foreground "#E6E1DC"))))
     (mode-line-buffer-id ((t (:background "#282828" :foreground "#E6E1DC"))))
     (mode-line-mousable ((t (:background "#282828" :foreground "#E6E1DC"))))
     (mode-line-mousable-minor-mode ((t (:background"#282828" :foreground "#E6E1DC"))))

     (mouse ((t (nil))))
     (next-error ((t (:foreground "black" :background "light gray"))))
     (nobreak-space ((t (:foreground "cyan" :underline t))))
     (nxml-attribute-colon-face ((t (:foreground "#33aaff"))))
     (nxml-attribute-local-name-face ((t (:foreground "#33aaff"))))
     (nxml-attribute-prefix-face ((t (:foreground "#33aaff"))))
     (nxml-attribute-value-delimiter-face ((t (:bold t :weight bold))))
     (nxml-attribute-value-face ((t (:foreground "gray"))))
     (nxml-cdata-section-CDATA-face ((t (:foreground "#33aaff"))))
     (nxml-cdata-section-content-face ((t (nil))))
     (nxml-cdata-section-delimiter-face ((t (:bold t :weight bold))))
     (nxml-char-ref-delimiter-face ((t (nil))))
     (nxml-char-ref-number-face ((t (nil))))
     (nxml-comment-content-face ((t (:italic t :slant italic))))
     (nxml-comment-delimiter-face ((t (:bold t :weight bold))))
     (nxml-delimited-data-face ((t (:foreground "gray"))))
     (nxml-delimiter-face ((t (:bold t :weight bold))))
     (nxml-element-colon-face ((t (:foreground "#33aaff"))))
     (nxml-element-local-name-face ((t (:foreground "#33aaff"))))
     (nxml-element-prefix-face ((t (:foreground "#33aaff"))))
     (nxml-entity-ref-delimiter-face ((t (nil))))
     (nxml-entity-ref-name-face ((t (nil))))
     (nxml-glyph-face ((t (:background "light grey" :foreground "black" :slant normal :weight normal :foundry "misc" :family "fixed"))))
     (nxml-hash-face ((t (:foreground "#33aaff"))))
     (nxml-markup-declaration-delimiter-face ((t (:bold t :weight bold))))
     (nxml-name-face ((t (:foreground "#33aaff"))))
     (nxml-namespace-attribute-colon-face ((t (:foreground "#33aaff"))))
     (nxml-namespace-attribute-prefix-face ((t (:foreground "#33aaff"))))
     (nxml-namespace-attribute-value-delimiter-face ((t (:bold t :weight bold))))
     (nxml-namespace-attribute-value-face ((t (:foreground "gray"))))
     (nxml-namespace-attribute-xmlns-face ((t (:foreground "#33aaff"))))
     (nxml-processing-instruction-content-face ((t (:foreground "gray"))))
     (nxml-processing-instruction-delimiter-face ((t (:bold t :weight bold))))
     (nxml-processing-instruction-target-face ((t (:foreground "#33aaff"))))
     (nxml-prolog-keyword-face ((t (:foreground "#33aaff"))))
     (nxml-prolog-literal-content-face ((t (:foreground "gray"))))
     (nxml-prolog-literal-delimiter-face ((t (:bold t :weight bold))))
     (nxml-ref-face ((t (nil))))
     (nxml-tag-delimiter-face ((t (:bold t :weight bold))))
     (nxml-tag-slash-face ((t (:foreground "#33aaff"))))
     (nxml-text-face ((t (nil))))

     ;; org-mode
     (org-agenda-column-dateline ((t (:family "Terminus" :weight normal :slant normal :underline nil :strike-through nil :foreground "white" :background "#141414" :height 120))))
     (org-agenda-date ((t (:foreground "Blue1"))))
     (org-agenda-date-today ((t (:italic t :bold t :foreground "Blue1" :slant italic :weight bold))))
     (org-agenda-date-weekend ((t (:bold t :foreground "Blue1" :weight bold))))
     (org-agenda-dimmed-todo-face ((t (:foreground "grey50"))))
     (org-agenda-done ((t (:foreground "PaleGreen"))))
     (org-agenda-restriction-lock ((t (:background "skyblue4"))))
     (org-agenda-structure ((t (:foreground "#008ed1"))))
     (org-archived ((t (:foreground "grey70"))))
     (org-block ((t (:foreground "grey70"))))
     (org-checkbox ((t (:bold t :weight bold))))
     (org-clock-overlay ((t (:background "SkyBlue4"))))
     (org-code ((t (:foreground "grey70"))))
     (org-column ((t (:background "#141414" :foreground "white" :strike-through nil :underline nil :slant normal :weight normal :height 120 :family "Terminus"))))
     (org-column-title ((t (:bold t :background "grey30" :underline t :weight bold))))
     (org-date ((t (:foreground "#777"))))
     (org-done ((t (:bold t :foreground "#555" :weight bold))))
     (org-drawer ((t (:foreground "LightSkyBlue"))))
     (org-ellipsis ((t (:foreground "white"))))
     (org-footnote ((t (:foreground "Cyan" :underline t))))
     (org-formula ((t (:foreground "chocolate1"))))
     (org-headline-done ((t (:foreground "LightSalmon"))))
     (org-hide ((t (:foreground "black"))))
     (org-latex-and-export-specials ((t (:foreground "burlywood"))))
     (org-level-1 ((t (:foreground "#5555ff"))))
     (org-level-2 ((t (:foreground "#edd400"))))
     (org-level-3 ((t (:foreground "#6ac214"))))
     (org-level-4 ((t (:foreground "tomato"))))
     (org-level-5 ((t (:foreground "#b9fc6d"))))
     (org-level-6 ((t (:foreground "purple"))))
     (org-level-7 ((t (:foreground "#5555ff"))))
     (org-level-8 ((t (:foreground "#ffff55"))))
     (org-link ((t (:foreground "white" :underline t))))
     (org-meta-line ((t (:foreground "#008ed1"))))
     (org-mode-line-clock ((t (:background "grey75" :foreground "black" :box (:line-width -1 :style released-button)))))
     (org-property-value ((t (nil))))
     (org-scheduled ((t (:foreground "#00bb00"))))
     (org-scheduled-previously ((t (:foreground "#00bb00"))))
     (org-scheduled-today ((t (:foreground "#55ff55"))))
     (org-sexp-date ((t (:foreground "Cyan"))))
     (org-special-keyword ((t (:foreground "#00bb00"))))
     (org-table ((t (:foreground "#555"))))
     (org-tag ((t (:bold t :foreground "#55ff55" :weight bold))))
     (org-target ((t (:underline t))))
     (org-time-grid ((t (:foreground "#555"))))
     (org-todo ((t (:bold t :foreground "#ff5555" :weight bold))))
     (org-upcoming-deadline ((t (:foreground "#ff5555"))))
     (org-verbatim ((t (:foreground "grey70"))))
     (org-warning ((t (:foreground "#ee3c3c"))))




     (outline-1 ((t (:foreground "firebrick"))))
     (outline-2 ((t (:foreground "SeaGreen"))))
     (outline-3 ((t (:foreground "MediumBlue"))))
     (outline-4 ((t (:foreground "DarkGreen"))))
     (outline-5 ((t (:foreground "SteelBlue"))))
     (outline-6 ((t (:foreground "gray"))))
     (outline-7 ((t (:foreground "SlateBlue"))))
     (outline-8 ((t (:foreground "RoyalBlue"))))
     (pabbrev-debug-display-label-face ((t (:underline "navy"))))
     (pabbrev-suggestions-face ((t (:foreground "PaleGreen"))))
     (pabbrev-suggestions-label-face ((t (nil))))
     (pulse-highlight-face ((t (:background "#AAAA33"))))
     (pulse-highlight-start-face ((t (:background "#AAAA33"))))
     (query-replace ((t (:foreground "brown4" :background "palevioletred2"))))
     (region ((t (:background "light gray" :foreground "black"))))
     (scroll-bar ((t (nil))))
     (secondary-selection ((t (:background "SkyBlue4"))))
     (semantic-decoration-on-fileless-includes ((t (:background "#009000"))))
     (semantic-decoration-on-includes ((t (nil))))
     (semantic-decoration-on-private-members-face ((t (:background "#200000"))))
     (semantic-decoration-on-protected-members-face ((t (:background "#000020"))))
     (semantic-decoration-on-unknown-includes ((t (:background "#900000"))))
     (semantic-decoration-on-unparsed-includes ((t (:background "#555500"))))
     (semantic-highlight-edits-face ((t (:background "gray20"))))
     (semantic-highlight-func-current-tag-face ((t (:background "gray20"))))
     (semantic-tag-boundary-face ((t (:overline "cyan"))))
     (semantic-unmatched-syntax-face ((t (:underline "red"))))
     (senator-intangible-face ((t (:foreground "gray75"))))
     (senator-momentary-highlight-face ((t (:background "gray30"))))
     (senator-read-only-face ((t (:background "#664444"))))
     (sh-escaped-newline ((t (:foreground "RoyalBlue"))))
     (sh-heredoc ((t (:bold t :foreground "yellow1" :weight bold))))
     (sh-quoted-exec ((t (:foreground "salmon"))))
     (shadow ((t (:foreground "grey70"))))
     (show-paren-match ((t (:background "steelblue3"))))
     (show-paren-mismatch ((t (:background "purple" :foreground "white"))))
     (speedbar-button-face ((t (:foreground "green3"))))
     (speedbar-directory-face ((t (:foreground "light blue"))))
     (speedbar-file-face ((t (:foreground "cyan"))))
     (speedbar-highlight-face ((t (:background "sea green"))))
     (speedbar-selected-face ((t (:foreground "red" :underline t))))
     (speedbar-separator-face ((t (:background "blue" :foreground "white" :overline "gray"))))
     (speedbar-tag-face ((t (:foreground "yellow"))))
     (success ((t (:bold t :foreground "Green1" :weight bold))))
     (tool-bar ((t (:background "grey75" :foreground "black" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:family "Sans Serif" :background "lightyellow" :foreground "black"))))
     (trailing-whitespace ((t (:background "red1"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "Sans Serif"))))
     (vertical-border ((t (nil))))
     (warning ((t (:bold t :foreground "DarkOrange" :weight bold))))
     (which-func ((t (:foreground "Blue1"))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red1"))))
     (widget-documentation ((t (:foreground "lime green"))))
     (widget-field ((t (:background "dim gray"))))
     (widget-inactive ((t (:foreground "grey70"))))
     (widget-single-line-field ((t (:background "dim gray")))))))
(add-to-list 'color-themes '(color-theme-ola-dark  "Ola Dark" "Ola Bini"))

(provide 'color-theme-ola-dark)
